from pathlib import Path

CURATED_SEEDS = {
    "tongue_twister": [
        {"text": "She sells seashells by the seashore.", "target_phoneme": "s/sh", "age_group_hint": "child"},
        {"text": "How much wood would a woodchuck chuck if a woodchuck could chuck wood?", "target_phoneme": "w/ch", "age_group_hint": "child"},
        {"text": "Peter Piper picked a peck of pickled peppers.", "target_phoneme": "p", "age_group_hint": "child"},
        {"text": "Red lorry, yellow lorry.", "target_phoneme": "r/l", "age_group_hint": "child"},
        {"text": "The thirty-three thieves thought that they thrilled the throne throughout Thursday.", "target_phoneme": "th", "age_group_hint": "teen"},
        {"text": "Eleven benevolent elephants.", "target_phoneme": "l/el", "age_group_hint": "child"},
        {"text": "Which witch switched the Swiss wristwatches?", "target_phoneme": "w/ch/sw", "age_group_hint": "teen"},
        {"text": "A skunk sat on a stump and thunk the stump stunk, but the stump thunk the skunk stunk.", "target_phoneme": "st/sk/th", "age_group_hint": "teen"},
        {"text": "Fresh French fried fish and chips.", "target_phoneme": "fr/ch", "age_group_hint": "child"},
        {"text": "Six slippery snails slid slowly seaward.", "target_phoneme": "s/sl", "age_group_hint": "youth"},
        {"text": "Betty Botter bought some butter, but the butter Betty bought was bitter.", "target_phoneme": "b/t", "age_group_hint": "child"},
        {"text": "Through three cheese trees three free fleas flew.", "target_phoneme": "th/fr/fl", "age_group_hint": "teen"},
        {"text": "Unique New York, unique New York, you know you need unique New York.", "target_phoneme": "ny/y", "age_group_hint": "youth"},
        {"text": "I scream, you scream, we all scream for ice cream.", "target_phoneme": "scr/cr", "age_group_hint": "child"},
        {"text": "Lesser leather never weathered wetter weather better.", "target_phoneme": "l/w/th", "age_group_hint": "teen"},
    ],
    "yes_and_improv": [
        {"text": "You're an astronaut who just discovered the moon is made of cheese.", "age_group_hint": "child"},
        {"text": "You're opening a restaurant that only serves breakfast food at midnight.", "age_group_hint": "teen"},
        {"text": "You wake up one morning and everything you touch turns into a musical instrument.", "age_group_hint": "child"},
        {"text": "Your school decides to replace all teachers with robots for one week.", "age_group_hint": "teen"},
        {"text": "You find a door in your bedroom that leads to a completely different city.", "age_group_hint": "youth"},
        {"text": "A scientist accidentally makes a potion that lets animals talk.", "age_group_hint": "child"},
        {"text": "You've been hired as a professional taste tester for the world's strangest candies.", "age_group_hint": "teen"},
    ],
    "no_but_improv": [
        {"text": "Someone suggests your town should replace all cars with horses.", "age_group_hint": "teen"},
        {"text": "Your friend wants to rename your school after a popular video game character.", "age_group_hint": "teen"},
        {"text": "Your parents propose a rule that bedtime is now at 6pm.", "age_group_hint": "child"},
        {"text": "A classmate proposes the school cafeteria should only serve desserts.", "age_group_hint": "child"},
        {"text": "Your city wants to ban all smartphones for people under 18.", "age_group_hint": "youth"},
        {"text": "Your teacher wants to do all lessons outside in the park, even in winter.", "age_group_hint": "teen"},
    ],
    "silly_topic_debate": [
        {"topic": "Cats are better pets than dogs", "age_group_hint": "child"},
        {"topic": "Pizza should be considered a vegetable", "age_group_hint": "child"},
        {"topic": "Summer vacation is too long", "age_group_hint": "teen"},
        {"topic": "Homework should be banned on weekends", "age_group_hint": "teen"},
        {"topic": "Aliens are probably friendly", "age_group_hint": "child"},
        {"topic": "Superheroes would do more harm than good in real life", "age_group_hint": "youth"},
        {"topic": "Video games are better than books for learning", "age_group_hint": "teen"},
        {"topic": "Robots should be allowed to compete in the Olympics", "age_group_hint": "youth"},
        {"topic": "School should start at noon", "age_group_hint": "teen"},
        {"topic": "Time travel would ruin history", "age_group_hint": "youth"},
    ],
    "audio_postcard": [
        {"prompt": "Describe your favourite place in your school to someone who has never visited.", "age_group_hint": "child"},
        {"prompt": "Imagine you spent a week in a place with no internet. Tell someone what you discovered about yourself.", "age_group_hint": "youth"},
        {"prompt": "Send a postcard from the last holiday or weekend trip you took — real or imaginary.", "age_group_hint": "teen"},
        {"prompt": "Describe a normal school morning from the perspective of your backpack.", "age_group_hint": "child"},
        {"prompt": "Record a postcard to your future self five years from now.", "age_group_hint": "teen"},
        {"prompt": "Describe your neighbourhood as if explaining it to someone from another country.", "age_group_hint": "youth"},
    ],
    "paragraph_reading": [
        {"text": "The fox and the crow. A crow was sitting on a branch of a tree with a piece of cheese in her beak when a fox observed her and set his wits to work to discover some way of getting the cheese. Coming and standing under the tree he looked up and said, what a noble bird I see above me. Her beauty is without equal. If only her voice is as sweet as her looks are fair, she ought without doubt to be queen of the birds. The crow was hugely flattered by this, and just to show the fox that she could sing she gave a loud caw. Down came the cheese, of course, and the fox, snatching it up, said, you have a voice, madam, but what you want is wits.", "age_group_hint": "child"},
        {"text": "The tortoise and the hare. The hare was once boasting of his speed before the other animals. I have never yet been beaten, said he, when I put forth my full speed. I challenge anyone here to race with me. The tortoise said quietly, I accept your challenge. That is a good joke, said the hare. I could dance round you all the way. Keep your boasting until you have beaten me, answered the tortoise. They agreed on a route and started off together. The hare darted almost out of sight at once, but soon stopped and, to show his contempt for the tortoise, lay down to have a nap. The tortoise plodded on and on, and when the hare awoke from his nap he saw the tortoise just near the winning post and could not run up in time to save the race.", "age_group_hint": "child"},
        {"text": "Every morning before school, Marcus would pack his bag with the same things: one notebook, two pencils, a water bottle, and a small photograph of his dog. He had carried this photograph every day for three years, ever since his family moved to the city. The school was bigger than anything he had known before. The hallways seemed to go on forever, and the cafeteria could seat five hundred students at once. But Marcus had found his favourite spot: a small bench behind the library, where the noise faded and the trees were tall enough to remind him of home.", "age_group_hint": "teen"},
        {"text": "Scientists have long wondered why certain birds migrate thousands of miles each year. The Arctic tern, for example, travels from its breeding grounds in the Arctic all the way to Antarctica and back, a round trip of nearly seventy thousand kilometres. Researchers now believe that these birds navigate using a combination of the sun, the stars, and the Earth's magnetic field. Young birds learn the basic direction from their parents, but over time they develop an extraordinary internal map that allows them to return to the exact same location year after year, even without ever having made the journey before.", "age_group_hint": "youth"},
        {"text": "The first successful powered flight lasted only twelve seconds. On December 17, 1903, Orville Wright piloted a fragile machine made of wood, cloth, and wire across a windswept beach in North Carolina. His brother Wilbur ran alongside, steadying the wing. The aircraft, which they called the Flyer, rose to a height of about three metres and covered thirty seven metres before landing. They flew four times that morning. Few people witnessed the event, and the newspapers barely noticed. Yet within a decade, aeroplanes were crossing continents. Within sixty years, humans had reached the edge of space.", "age_group_hint": "teen"},
        {"text": "In the deep ocean, sunlight cannot reach. Below two hundred metres, the water is completely dark and the pressure is enormous. Yet life thrives here in surprising abundance. Creatures that glow in the dark drift through the blackness, hunting and being hunted. The anglerfish dangles a luminous lure from its forehead to attract prey. The vampire squid spreads a cloak of webbed arms to trap particles of food. Giant tube worms cluster around hydrothermal vents, where superheated water rich in minerals provides the energy that drives entire ecosystems, without any sunlight at all.", "age_group_hint": "youth"},
        {"text": "Rosa had never spoken in front of the whole class before. Her teacher had announced a poetry reading, and every student was expected to stand at the front and recite three stanzas from memory. For two weeks Rosa had practised in her bedroom, whispering the words into her mirror each night. She knew the poem perfectly when she was alone. But standing up there, with thirty pairs of eyes looking at her, her mind went completely blank. She took one slow breath. Then another. And then, from somewhere deep in her memory, the first line came.", "age_group_hint": "teen"},
    ],
    "poem_recitation": [
        {"text": "The Road Not Taken by Robert Frost.\nTwo roads diverged in a yellow wood,\nAnd sorry I could not travel both\nAnd be one traveler, long I stood\nAnd looked down one as far as I could\nTo where it bent in the undergrowth.", "stress_pattern": "iambic", "emotional_tone": "reflective", "age_group_hint": "youth"},
        {"text": "Stopping by Woods on a Snowy Evening by Robert Frost.\nWhose woods these are I think I know.\nHis house is in the village though;\nHe will not see me stopping here\nTo watch his woods fill up with snow.", "stress_pattern": "iambic", "emotional_tone": "peaceful", "age_group_hint": "teen"},
        {"text": "Hope is the thing with feathers by Emily Dickinson.\nHope is the thing with feathers\nThat perches in the soul,\nAnd sings the tune without the words,\nAnd never stops at all.", "stress_pattern": "common metre", "emotional_tone": "uplifting", "age_group_hint": "youth"},
        {"text": "The Owl and the Pussy-cat by Edward Lear.\nThe Owl and the Pussy-cat went to sea\nIn a beautiful pea-green boat,\nThey took some honey, and plenty of money,\nWrapped up in a five-pound note.", "stress_pattern": "anapestic", "emotional_tone": "playful", "age_group_hint": "child"},
        {"text": "If by Rudyard Kipling.\nIf you can keep your head when all about you\nAre losing theirs and blaming it on you,\nIf you can trust yourself when all men doubt you,\nBut make allowance for their doubting too.", "stress_pattern": "iambic", "emotional_tone": "inspiring", "age_group_hint": "youth"},
        {"text": "The New Colossus by Emma Lazarus.\nNot like the brazen giant of Greek fame,\nWith conquering limbs astride from land to land;\nHere at our sea-washed, sunset gates shall stand\nA mighty woman with a torch, whose flame\nIs the imprisoned lightning, and her name\nMother of Exiles.", "stress_pattern": "iambic pentameter", "emotional_tone": "powerful", "age_group_hint": "adult"},
        {"text": "Bed in Summer by Robert Louis Stevenson.\nIn winter I get up at night\nAnd dress by yellow candle-light.\nIn summer, quite the other way,\nI have to go to bed by day.", "stress_pattern": "iambic", "emotional_tone": "playful", "age_group_hint": "child"},
        {"text": "I Wandered Lonely as a Cloud by William Wordsworth.\nI wandered lonely as a cloud\nThat floats on high o'er vales and hills,\nWhen all at once I saw a crowd,\nA host, of golden daffodils;\nBeside the lake, beneath the trees,\nFluttering and dancing in the breeze.", "stress_pattern": "iambic", "emotional_tone": "joyful", "age_group_hint": "teen"},
    ],
    "rapid_fire_qa": [
        {"text": "What is the capital city of France?", "expected_answer": "Paris", "age_group_hint": "child"},
        {"text": "How many sides does a hexagon have?", "expected_answer": "Six", "age_group_hint": "child"},
        {"text": "What planet is closest to the Sun?", "expected_answer": "Mercury", "age_group_hint": "teen"},
        {"text": "Who wrote Romeo and Juliet?", "expected_answer": "Shakespeare", "age_group_hint": "teen"},
        {"text": "What is the chemical symbol for water?", "expected_answer": "H2O", "age_group_hint": "teen"},
        {"text": "In which continent is the Amazon rainforest located?", "expected_answer": "South America", "age_group_hint": "child"},
        {"text": "What is the square root of 144?", "expected_answer": "12", "age_group_hint": "teen"},
        {"text": "What gas do plants absorb from the atmosphere during photosynthesis?", "expected_answer": "Carbon dioxide", "age_group_hint": "teen"},
        {"text": "Name the longest river in the world.", "expected_answer": "The Nile", "age_group_hint": "youth"},
        {"text": "What is the name of the force that keeps planets in orbit around the Sun?", "expected_answer": "Gravity", "age_group_hint": "teen"},
        {"text": "How many bones are in the adult human body?", "expected_answer": "206", "age_group_hint": "youth"},
        {"text": "What year did the First World War begin?", "expected_answer": "1914", "age_group_hint": "youth"},
        {"text": "What is the powerhouse of the cell?", "expected_answer": "The mitochondria", "age_group_hint": "teen"},
        {"text": "Name the author of Harry Potter.", "expected_answer": "J.K. Rowling", "age_group_hint": "child"},
        {"text": "What is the fastest land animal?", "expected_answer": "The cheetah", "age_group_hint": "child"},
    ],
    "roleplay": [
        {"text": "You are a student who needs to explain to your teacher why you did not complete your homework.", "student_role": "student", "ai_role": "teacher", "scenario": "classroom", "age_group_hint": "teen"},
        {"text": "You are ordering food at a restaurant for the first time by yourself.", "student_role": "customer", "ai_role": "waiter", "scenario": "restaurant", "age_group_hint": "child"},
        {"text": "You are calling a doctor's office to make an appointment for a check-up.", "student_role": "patient", "ai_role": "receptionist", "scenario": "medical", "age_group_hint": "youth"},
        {"text": "You are asking a librarian to help you find books about space exploration.", "student_role": "student", "ai_role": "librarian", "scenario": "library", "age_group_hint": "child"},
        {"text": "You are a new student introducing yourself to a classmate on your first day at a new school.", "student_role": "new student", "ai_role": "classmate", "scenario": "school", "age_group_hint": "teen"},
        {"text": "You are at a job interview for a part-time position at a local bookshop.", "student_role": "applicant", "ai_role": "interviewer", "scenario": "job interview", "age_group_hint": "youth"},
        {"text": "You are explaining to a younger sibling why it is important to brush their teeth every day.", "student_role": "older sibling", "ai_role": "younger sibling", "scenario": "home", "age_group_hint": "teen"},
        {"text": "You are buying a birthday gift at a shop but need help deciding what to get.", "student_role": "customer", "ai_role": "shop assistant", "scenario": "retail", "age_group_hint": "child"},
        {"text": "You are reporting a lost wallet to a police officer.", "student_role": "citizen", "ai_role": "police officer", "scenario": "public", "age_group_hint": "youth"},
        {"text": "You are asking your neighbour if you can borrow their bicycle for the afternoon.", "student_role": "neighbour", "ai_role": "neighbour", "scenario": "neighbourhood", "age_group_hint": "teen"},
    ],
    "short_speech": [
        {"text": "Why school uniforms should be abolished", "outline": ["hook: describe a typical uniform morning", "argument 1: self-expression matters for development", "argument 2: cost burden on families", "conclusion: learning is about minds, not matching clothes"], "age_group_hint": "teen"},
        {"text": "The importance of sleep for teenagers", "outline": ["hook: how many hours did you sleep last night", "fact: teenagers need 8-10 hours", "consequence: sleep deprivation affects memory and mood", "call to action: treat sleep like homework"], "age_group_hint": "teen"},
        {"text": "Why every school should have a garden", "outline": ["hook: where does your food come from", "benefit 1: teaches responsibility", "benefit 2: connects students to nature", "conclusion: gardens grow more than plants"], "age_group_hint": "child"},
        {"text": "Should social media have an age limit", "outline": ["hook: statistic on student phone use", "argument for: mental health concerns", "argument against: digital literacy needs early start", "personal stance and conclusion"], "age_group_hint": "youth"},
        {"text": "The life of a remarkable animal: the octopus", "outline": ["hook: octopus opening a jar", "intelligence: problem solving and memory", "biology: three hearts, blue blood", "closing: why we should protect ocean habitats"], "age_group_hint": "teen"},
        {"text": "Why reading fiction makes you a better person", "outline": ["hook: name a character who changed your thinking", "empathy: walking in another's shoes", "vocabulary and imagination benefits", "challenge: read one new book this month"], "age_group_hint": "youth"},
    ],
    "story_building": [
        {"text": "The old lighthouse had been dark for fifty years. Nobody knew why the light came on the night Maya walked past it alone.", "genre": "mystery", "age_group_hint": "teen"},
        {"text": "On the last day of school, someone left a mysterious envelope on every desk in Class 6B. Inside each one was a single key.", "genre": "adventure", "age_group_hint": "child"},
        {"text": "The robot had been sitting in the corner of the classroom for three weeks before anyone noticed it was taking notes.", "genre": "science fiction", "age_group_hint": "teen"},
        {"text": "Every Saturday morning, the old woman at the end of the street put something different in her window. This week it was a compass pointing the wrong direction.", "genre": "mystery", "age_group_hint": "youth"},
        {"text": "The dragon was very small, about the size of a cat, and it was terrified of fire.", "genre": "fantasy", "age_group_hint": "child"},
        {"text": "When the power went out across the whole city, people did something nobody expected: they came outside.", "genre": "realistic fiction", "age_group_hint": "youth"},
        {"text": "She had been collecting stones her whole life, but this one was different. It was warm, even in winter, and it seemed to hum.", "genre": "fantasy", "age_group_hint": "teen"},
        {"text": "The substitute teacher knew everyone's name before they had even introduced themselves. Nobody could figure out how.", "genre": "mystery", "age_group_hint": "teen"},
    ],
}

SOURCES = {
    "paragraph_reading": [
        ("https://gutendex.com/books/?search=children&languages=en&mime_type=text%2Fplain", "child", "gutenberg:children"),
        ("https://gutendex.com/books/?search=short+stories&languages=en&mime_type=text%2Fplain", "teen", "gutenberg:short_stories"),
    ],
    "poem_recitation": [
        ("https://gutendex.com/books/?search=poems&languages=en&mime_type=text%2Fplain", "teen", "gutenberg:poetry"),
    ],
    "story_building": [
        ("https://gutendex.com/books/?search=fairy+tales&languages=en&mime_type=text%2Fplain", "child", "gutenberg:fairy_tales"),
    ],
    "rapid_fire_qa":   [],
    "roleplay":        [],
    "short_speech":    [],
    "yes_and_improv":  [],
    "no_but_improv":   [],
    "silly_topic_debate": [],
    "audio_postcard":  [],
    "tongue_twister":  [],
}

CURATED_ONLY = {
    lt for lt, srcs in SOURCES.items() if not srcs
}